### ISSUE TITLE
Doesn't work correctly with relative `cwd` option

### ISSUE THREAD

**Issue by JKillian** [js-cli/node-findup-sync#31] opened 2016-04-11 22:12 UTC
**Not so hypothetical scenario**

```
findup('tslint.json', {cwd: 'path/to/dir'});
```

**Issue explanation**
```
var cwd = resolveDir(options.cwd || ''");
```

is run. `cwd` now equals `'path/to/dir'` as explained in the [resolve-dir docs](https://github.com/jonschlinkert/resolve-dir).

The `findFile` function doesn't handle this relative path correctly: it traverses these paths:

1. `./path/to/dir/tslint.json`
2. `./path/to/tslint.json`
3. `./path/tslint.json`
4. `/tslint.json`

There's huge gap here in that nothing between CWD + "path/tslint.json" and "/tslint.json" is searched

**Comment by jonschlinkert** [comment] 2016-04-11 22:35
is this a resolve-dir issue or findup-sync issue?  if resolve-dir please close this issue and re-create the issue on resolve-dir so we can get it solved.

**Comment by JKillian** [comment] 2016-04-11 22:41
I guess it depends what `resolve-dir` is supposed to do? In this case, resolve-dir is doing exactly what its docs describe:

>  Returns a local directory path unchanged

```js
resolve('a')
//=> 'a'
```

The issue is that `findup-sync`'s algorithm doesn't handle that type of result very well.

**Comment by jonschlinkert** [comment] 2016-04-11 22:41
also fwiw I'm reviewing the linked issue. I unfortunately won't be online as long today as I normally am, but I will get this resolved asap

**Comment by jonschlinkert** [comment] 2016-04-11 22:42
> The issue is that findup-sync's algorithm doesn't handle that type of result very well.

meaning that you want findup-sync to also recurse "down" like glob? this might be totally reasonable, so don't take that question as a challenge, I really would like to know what you think

**Comment by JKillian** [comment] 2016-04-11 22:47
> meaning that you want findup-sync to also recurse "down" like glob?

I think so, although I'm not 100% sure of what you mean by "down" here.  

As an example though, let's say my process's cwd is "a/b", and I call `findup("file.txt", {cwd: "c/d"})`. I'd expect that the following paths would be searched in this order:

1. `a/b/c/d/file.txt`
2. `a/b/c/file.txt`
3. `a/b/file.txt`
4. `a/file.txt`
5. `/file.txt`

(With the way things are right now, 3 and 4 are getting skipped)

**Comment by JKillian** [comment] 2016-04-11 22:49
> also fwiw I'm reviewing the linked issue. I unfortunately won't be online as long today as I normally am, but I will get this resolved asap

No worries, there's no hurry on my end on getting this fixed. Rolling back to `0.3.0` of `findup-sync` should fix things for me for now

**Comment by jonschlinkert** [comment] 2016-04-11 23:19
> although I'm not 100% sure of what you mean by "down" here.

Typically, glob finds files by recursing "down" into child directories. So using your examples, given `./**/*.txt` glob would recurse through `a/`, then `a/b/` then `a/b/c/` and so on. 

This library finds "up", by going in the opposite direction as glob. 

> With the way things are right now, 3 and 4 are getting skipped

if that's the case then it it's bug here. It makes sense that this would have always worked before because - even if findup-sync hadn't properly handled those directories - for every directory "found up",  glob would have recursed back "down" into all child directories, depending on the greediness of the glob pattern. This kind of broad zig-zag search pattern can have a noticeably negative impact on user experience, so ideally we can avoid using glob for anything in this lib. (not that glob is slow, it's the compounding zig-zag pattern. it's usually fast when a file exists, but exponentially slower otherwise - because glob and findup-sync will keep looking until everything is exhausted)

anyway, it looks like we have a bug that needs to be fixed - findup-sync should be hitting those dirs. It also looks like it should be a pretty easy fix. I'll try to get something pushed up in the next day or two

**Comment by jonschlinkert** [comment] 2016-04-11 23:19
also thanks for the additional detail, really helpful

**Comment by JKillian** [comment] 2016-04-12 00:24
Ah, gotchya what you mean with "down" vs. "up" now. Nope, definitely don't want it to search "down", just traversing up through parent directories is what I expect.

(As a sidenote, that's an interesting concept how you can easily fall into a slow zig-zag pattern when moving up and using a glob!)

**Comment by sttk** [comment] 2016-04-29 13:11
Is it a problem on Windows?
I encountered a problem like this on Windows.

```js
const findup = require('findup-sync');
console.log(findup('app.json', { cwd: 'aaa/bbb/ccc'}));   // => null
console.log(findup('app.json', { cwd: 'aaa\\bbb\\ccc'}));  // => aaa/app.json
console.log(findup('aaa/app.json'));  // => aaa/app.json
```
If so, this cause is using only `path.sep` to separate `cwd` in findup-sync. This can avoid by applying `path.resolve` to `cwd` before passing it to findup, though.

**Comment by sttk** [comment] 2016-04-29 13:58
I'm sorry that I misunderstand this issue.

@JKillian 's problem is that finding path becomes `/tslint.json` and it also happens on other platform.

And the cause is here:
https://github.com/js-cli/node-findup-sync/blob/master/index.js#L81

By modifying this part to a line like following, the result becomes correct. (Though the following code is temporary)

```js
fp = (cwd ? cwd + '/' : '') + filename;
```

**Comment by sttk** [comment] 2016-04-29 15:27
Oops, I'm sorry again for my misunderstanding.

@JKillian 's problem would be that findup-sync skips upper directories from `cwd` and jumps to '/' for finding. And the cause is handling `cwd` at around the same position with above.

**Comment by jonschlinkert** [comment] 2016-04-29 21:21
@sttk thanks for the comments, this helps. sorry again for the delay. I've started looking to this. It's on my priority list for the weekend.

**Comment by rosskevin** [comment] 2016-05-02 22:56
It appears that `cwd` also doesn't work with the latest using `0.4.0` with `micromatch` either.  Strangely, `micromatch` doesn't even list `cwd` as an option but I see it in the code.

This is more broken than it was in the last npm version.

I'm in a lower `spec/dummy` directory and looking up for `app/assets/stylesheets` and it is returning `null` e.g. 
```javascript
findup(`app/assets/stylesheets`, {
        cwd: '..'
})
```

This was working with the older npm version.

**Comment by jonschlinkert** [comment] 2016-05-03 00:12
> Strangely, micromatch doesn't even list cwd as an option but I see it in the code.

micromatch doesn't read from the file system, same as minimatch. The problem is cwd handling in this lib. I had a chance to look at it and should be able to push something up in the next day or so.

**Comment by jonschlinkert** [comment] 2016-05-07 10:39
I just pushed up some minor changes to [a branch](https://github.com/js-cli/node-findup-sync/tree/issue-31). It would be awesome if someone who was having issues with this could pull it down and let me know if it resolves the issue - and if not, maybe add a failing unit test if you have time. Thanks!

**Comment by sttk** [comment] 2016-05-07 11:43
@jonschlinkert I've checked that my problem is solved by the branch's module on macosx, linux, and windows. Awesome! Thanks!

**Comment by jonschlinkert** [comment] 2016-05-07 12:23
@sttk great thanks! Let's wait a bit to see if the OP can check as well. thank you

**Comment by jonschlinkert** [comment] 2016-05-10 10:58
I've also had a chance to test on windows and mac now, and no issues for me. 

Unless anyone has objections, I'm thinking we should go ahead and merge, since we know this at least solves the issue for some users.

**Comment by JKillian** [comment] 2016-05-10 14:37
Sorry I haven't had a chance to try out these changes! But at a brief glance, looks good to me, using `path.resolve` seems like a good way to take care of these issues

**Closed** 2016-05-19 04:16 UTC

**Comment by jonschlinkert** [comment] 2016-05-19 04:24
Sorry it took so long to publish! for some reason I had it in my mind that it was published already
